ROLE_SUPER_ADMIN = "super_admin"
ROLE_ADMIN = "admin"
ROLE_ROOT_ADMIN = "root_admin"
ROLE_TENANT_ADMIN = "tenant_admin"

PRIVILEGED_ADMIN_ROLE_NAMES = {ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_ROOT_ADMIN}
TENANT_ELEVATED_ROLE_NAMES = {ROLE_TENANT_ADMIN, ROLE_SUPER_ADMIN, ROLE_ADMIN, ROLE_ROOT_ADMIN}

